# k8s/rabbitmq-cluster.yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: iot-rabbitmq
  namespace: iot-rabbit
spec:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
  persistence:
    storage: 1Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
    additionalConfig: |
      mqtt.listeners.tcp.default = 1883
      mqtt.allow_anonymous = true
